services:
  sproxify:
    image: nginx:1.25-alpine
    container_name: sproxify
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

